name: Jekyll

on:
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Jekyll Build
      uses: jerryjvl/jekyll-build-action@v1
      env:
        JEKYLL_GITHUB_TOKEN: ${{ github.token }}
